# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1001, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.updateButton = QtWidgets.QPushButton(self.tab_1)
        self.updateButton.setGeometry(QtCore.QRect(160, 500, 111, 31))
        self.updateButton.setObjectName("updateButton")
        self.nameBox_tab1 = QtWidgets.QLineEdit(self.tab_1)
        self.nameBox_tab1.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.nameBox_tab1.setText("")
        self.nameBox_tab1.setObjectName("nameBox_tab1")
        self.pathBox_tab1 = QtWidgets.QLineEdit(self.tab_1)
        self.pathBox_tab1.setGeometry(QtCore.QRect(10, 130, 281, 20))
        self.pathBox_tab1.setText("")
        self.pathBox_tab1.setObjectName("pathBox_tab1")
        self.value_label_2 = QtWidgets.QLabel(self.tab_1)
        self.value_label_2.setGeometry(QtCore.QRect(810, 20, 171, 111))
        self.value_label_2.setObjectName("value_label_2")
        self.results_label = QtWidgets.QLabel(self.tab_1)
        self.results_label.setGeometry(QtCore.QRect(10, 160, 51, 21))
        self.results_label.setObjectName("results_label")
        self.saveButton = QtWidgets.QPushButton(self.tab_1)
        self.saveButton.setGeometry(QtCore.QRect(810, 370, 161, 31))
        self.saveButton.setObjectName("saveButton")
        self.projectTable = QtWidgets.QTableWidget(self.tab_1)
        self.projectTable.setGeometry(QtCore.QRect(810, 190, 161, 161))
        self.projectTable.setMaximumSize(QtCore.QSize(161, 16777215))
        self.projectTable.setObjectName("projectTable")
        self.projectTable.setColumnCount(1)
        self.projectTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.projectTable.setHorizontalHeaderItem(0, item)
        self.head_label = QtWidgets.QLabel(self.tab_1)
        self.head_label.setGeometry(QtCore.QRect(10, 0, 181, 21))
        self.head_label.setStyleSheet("text-decoration: underline;\n"
"font: 75 10pt \"Verdana\";")
        self.head_label.setObjectName("head_label")
        self.valueBox_tab1 = QtWidgets.QLineEdit(self.tab_1)
        self.valueBox_tab1.setGeometry(QtCore.QRect(350, 70, 113, 20))
        self.valueBox_tab1.setText("")
        self.valueBox_tab1.setObjectName("valueBox_tab1")
        self.path_label = QtWidgets.QLabel(self.tab_1)
        self.path_label.setGeometry(QtCore.QRect(10, 100, 121, 21))
        self.path_label.setObjectName("path_label")
        self.project_label_2 = QtWidgets.QLabel(self.tab_1)
        self.project_label_2.setGeometry(QtCore.QRect(350, 100, 121, 21))
        self.project_label_2.setObjectName("project_label_2")
        self.paraBox_tab1 = QtWidgets.QComboBox(self.tab_1)
        self.paraBox_tab1.setGeometry(QtCore.QRect(180, 70, 111, 22))
        self.paraBox_tab1.setObjectName("paraBox_tab1")
        self.paraBox_tab1.addItem("")
        self.paraBox_tab1.addItem("")
        self.projectBox_tab1 = QtWidgets.QLineEdit(self.tab_1)
        self.projectBox_tab1.setGeometry(QtCore.QRect(350, 130, 121, 20))
        self.projectBox_tab1.setText("")
        self.projectBox_tab1.setObjectName("projectBox_tab1")
        self.resultTab_tab1 = QtWidgets.QTableWidget(self.tab_1)
        self.resultTab_tab1.setGeometry(QtCore.QRect(10, 190, 761, 291))
        self.resultTab_tab1.setMinimumSize(QtCore.QSize(671, 0))
        self.resultTab_tab1.setObjectName("resultTab_tab1")
        self.resultTab_tab1.setColumnCount(8)
        self.resultTab_tab1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab1.setHorizontalHeaderItem(7, item)
        self.project_label = QtWidgets.QLabel(self.tab_1)
        self.project_label.setGeometry(QtCore.QRect(810, 160, 91, 21))
        self.project_label.setObjectName("project_label")
        self.drawButton = QtWidgets.QPushButton(self.tab_1)
        self.drawButton.setGeometry(QtCore.QRect(810, 450, 161, 31))
        self.drawButton.setObjectName("drawButton")
        self.exportButton = QtWidgets.QPushButton(self.tab_1)
        self.exportButton.setGeometry(QtCore.QRect(10, 500, 111, 31))
        self.exportButton.setObjectName("exportButton")
        self.value_label = QtWidgets.QLabel(self.tab_1)
        self.value_label.setGeometry(QtCore.QRect(350, 40, 91, 21))
        self.value_label.setObjectName("value_label")
        self.para_label = QtWidgets.QLabel(self.tab_1)
        self.para_label.setGeometry(QtCore.QRect(180, 40, 91, 21))
        self.para_label.setObjectName("para_label")
        self.name_label = QtWidgets.QLabel(self.tab_1)
        self.name_label.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.name_label.setObjectName("name_label")
        self.clearButton = QtWidgets.QPushButton(self.tab_1)
        self.clearButton.setGeometry(QtCore.QRect(810, 410, 161, 31))
        self.clearButton.setObjectName("clearButton")
        self.addButton = QtWidgets.QPushButton(self.tab_1)
        self.addButton.setGeometry(QtCore.QRect(310, 500, 111, 31))
        self.addButton.setObjectName("addButton")
        self.startButton = QtWidgets.QPushButton(self.tab_1)
        self.startButton.setGeometry(QtCore.QRect(660, 40, 111, 111))
        self.startButton.setObjectName("startButton")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.exportButton_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.exportButton_tab2.setGeometry(QtCore.QRect(840, 390, 131, 41))
        self.exportButton_tab2.setObjectName("exportButton_tab2")
        self.pathBox_tab2 = QtWidgets.QLineEdit(self.tab_2)
        self.pathBox_tab2.setGeometry(QtCore.QRect(320, 70, 281, 20))
        self.pathBox_tab2.setText("")
        self.pathBox_tab2.setObjectName("pathBox_tab2")
        self.resultTab_tab2 = QtWidgets.QTableWidget(self.tab_2)
        self.resultTab_tab2.setGeometry(QtCore.QRect(10, 130, 961, 221))
        self.resultTab_tab2.setMinimumSize(QtCore.QSize(671, 0))
        self.resultTab_tab2.setObjectName("resultTab_tab2")
        self.resultTab_tab2.setColumnCount(9)
        self.resultTab_tab2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTab_tab2.setHorizontalHeaderItem(8, item)
        self.results_label_3 = QtWidgets.QLabel(self.tab_2)
        self.results_label_3.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.results_label_3.setObjectName("results_label_3")
        self.head_label_tab2 = QtWidgets.QLabel(self.tab_2)
        self.head_label_tab2.setGeometry(QtCore.QRect(10, 0, 181, 21))
        self.head_label_tab2.setStyleSheet("text-decoration: underline;\n"
"font: 75 10pt \"Verdana\";")
        self.head_label_tab2.setObjectName("head_label_tab2")
        self.updateButton_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.updateButton_tab2.setGeometry(QtCore.QRect(700, 390, 131, 41))
        self.updateButton_tab2.setObjectName("updateButton_tab2")
        self.value_label_tab2 = QtWidgets.QLabel(self.tab_2)
        self.value_label_tab2.setGeometry(QtCore.QRect(810, 20, 171, 111))
        self.value_label_tab2.setObjectName("value_label_tab2")
        self.path_label_tab2 = QtWidgets.QLabel(self.tab_2)
        self.path_label_tab2.setGeometry(QtCore.QRect(320, 40, 121, 21))
        self.path_label_tab2.setObjectName("path_label_tab2")
        self.name_label_tab2 = QtWidgets.QLabel(self.tab_2)
        self.name_label_tab2.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.name_label_tab2.setObjectName("name_label_tab2")
        self.clearButton_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.clearButton_tab2.setGeometry(QtCore.QRect(700, 440, 131, 41))
        self.clearButton_tab2.setObjectName("clearButton_tab2")
        self.nameBox_tab2 = QtWidgets.QLineEdit(self.tab_2)
        self.nameBox_tab2.setGeometry(QtCore.QRect(10, 70, 111, 20))
        self.nameBox_tab2.setText("")
        self.nameBox_tab2.setObjectName("nameBox_tab2")
        self.limits_label = QtWidgets.QLabel(self.tab_2)
        self.limits_label.setGeometry(QtCore.QRect(160, 40, 81, 21))
        self.limits_label.setObjectName("limits_label")
        self.startButton_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.startButton_tab2.setGeometry(QtCore.QRect(660, 40, 111, 71))
        self.startButton_tab2.setObjectName("startButton_tab2")
        self.previewButton_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.previewButton_tab2.setGeometry(QtCore.QRect(840, 440, 131, 41))
        self.previewButton_tab2.setObjectName("previewButton_tab2")
        self.start_label_tab2_2 = QtWidgets.QLabel(self.tab_2)
        self.start_label_tab2_2.setGeometry(QtCore.QRect(10, 360, 51, 21))
        self.start_label_tab2_2.setObjectName("start_label_tab2_2")
        self.limitTable = QtWidgets.QTableWidget(self.tab_2)
        self.limitTable.setGeometry(QtCore.QRect(10, 390, 681, 91))
        self.limitTable.setObjectName("limitTable")
        self.limitTable.setColumnCount(6)
        self.limitTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.limitTable.setHorizontalHeaderItem(5, item)
        self.paraBox_tab2 = QtWidgets.QComboBox(self.tab_2)
        self.paraBox_tab2.setGeometry(QtCore.QRect(160, 70, 111, 22))
        self.paraBox_tab2.setObjectName("paraBox_tab2")
        self.paraBox_tab2.addItem("")
        self.paraBox_tab2.addItem("")
        self.paraBox_tab2.addItem("")
        self.paraBox_tab2.addItem("")
        self.paraBox_tab2.addItem("")
        self.paraBox_tab2.addItem("")
        self.paraBox_tab2.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.para_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.para_label_2.setGeometry(QtCore.QRect(860, 570, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.para_label_2.setFont(font)
        self.para_label_2.setObjectName("para_label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.updateButton.setText(_translate("MainWindow", "Update Table"))
        self.value_label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/KIT.png\"/></p></body></html>"))
        self.results_label.setText(_translate("MainWindow", "Results"))
        self.saveButton.setText(_translate("MainWindow", "Save Project"))
        item = self.projectTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Project Item"))
        self.head_label.setText(_translate("MainWindow", "ALiBaVa Search Tool"))
        self.path_label.setText(_translate("MainWindow", "Output path"))
        self.project_label_2.setText(_translate("MainWindow", "Project Name"))
        self.paraBox_tab1.setItemText(0, _translate("MainWindow", "Voltage"))
        self.paraBox_tab1.setItemText(1, _translate("MainWindow", "Annealing"))
        item = self.resultTab_tab1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor Name"))
        item = self.resultTab_tab1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Project"))
        item = self.resultTab_tab1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Run Number"))
        item = self.resultTab_tab1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Voltage"))
        item = self.resultTab_tab1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Annealing"))
        item = self.resultTab_tab1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Gain"))
        item = self.resultTab_tab1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Seed Signal"))
        item = self.resultTab_tab1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Draw"))
        self.project_label.setText(_translate("MainWindow", "Current Project"))
        self.drawButton.setText(_translate("MainWindow", "Draw Project"))
        self.exportButton.setText(_translate("MainWindow", "Export to File"))
        self.value_label.setText(_translate("MainWindow", "Search Value"))
        self.para_label.setText(_translate("MainWindow", "Search Parameter"))
        self.name_label.setText(_translate("MainWindow", "Sensor Name"))
        self.clearButton.setText(_translate("MainWindow", "Clear Project"))
        self.addButton.setText(_translate("MainWindow", ">> Add to Project"))
        self.startButton.setText(_translate("MainWindow", "Start Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "ALiBaVa Search Tool"))
        self.exportButton_tab2.setText(_translate("MainWindow", "Export"))
        item = self.resultTab_tab2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor Name"))
        item = self.resultTab_tab2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Project"))
        item = self.resultTab_tab2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ProbeID"))
        item = self.resultTab_tab2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fluence"))
        item = self.resultTab_tab2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Strip Para"))
        item = self.resultTab_tab2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Mean Value"))
        item = self.resultTab_tab2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "StdErr"))
        item = self.resultTab_tab2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Discard Ratio"))
        self.results_label_3.setText(_translate("MainWindow", "Results"))
        self.head_label_tab2.setText(_translate("MainWindow", "Strip Mean Calculator"))
        self.updateButton_tab2.setText(_translate("MainWindow", "Update"))
        self.value_label_tab2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/KIT.png\"/></p></body></html>"))
        self.path_label_tab2.setText(_translate("MainWindow", "Output path"))
        self.name_label_tab2.setText(_translate("MainWindow", "Sensor Name"))
        self.clearButton_tab2.setText(_translate("MainWindow", "Clear"))
        self.limits_label.setText(_translate("MainWindow", "Strip Parameter"))
        self.startButton_tab2.setText(_translate("MainWindow", "Start Search"))
        self.previewButton_tab2.setText(_translate("MainWindow", "Preview"))
        self.start_label_tab2_2.setText(_translate("MainWindow", "Limits"))
        item = self.limitTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lower Limit"))
        item = self.limitTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Upper Limit"))
        item = self.limitTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "R_int"))
        item = self.limitTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "R_poly_dc"))
        item = self.limitTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "I_leak_dc"))
        item = self.limitTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pinhole"))
        item = self.limitTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CC"))
        item = self.limitTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "C_int"))
        self.paraBox_tab2.setItemText(0, _translate("MainWindow", "*"))
        self.paraBox_tab2.setItemText(1, _translate("MainWindow", "R_int"))
        self.paraBox_tab2.setItemText(2, _translate("MainWindow", "R_poly_dc"))
        self.paraBox_tab2.setItemText(3, _translate("MainWindow", "I_leak_dc"))
        self.paraBox_tab2.setItemText(4, _translate("MainWindow", "Pinhole"))
        self.paraBox_tab2.setItemText(5, _translate("MainWindow", "CC"))
        self.paraBox_tab2.setItemText(6, _translate("MainWindow", "C_int"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Strip Mean Calculator"))
        self.para_label_2.setText(_translate("MainWindow", "Created by Marius Metzler"))

from Resources import Logo_rc
