# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\search_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startBox = QtWidgets.QLineEdit(self.centralwidget)
        self.startBox.setGeometry(QtCore.QRect(20, 80, 113, 20))
        self.startBox.setObjectName("startBox")
        self.endBox = QtWidgets.QLineEdit(self.centralwidget)
        self.endBox.setGeometry(QtCore.QRect(170, 80, 113, 20))
        self.endBox.setObjectName("endBox")
        self.head_label = QtWidgets.QLabel(self.centralwidget)
        self.head_label.setGeometry(QtCore.QRect(20, 10, 181, 21))
        self.head_label.setStyleSheet("text-decoration: underline;\n"
"font: 75 10pt \"Verdana\";")
        self.head_label.setObjectName("head_label")
        self.start_label = QtWidgets.QLabel(self.centralwidget)
        self.start_label.setGeometry(QtCore.QRect(20, 50, 51, 21))
        self.start_label.setObjectName("start_label")
        self.end_label = QtWidgets.QLabel(self.centralwidget)
        self.end_label.setGeometry(QtCore.QRect(170, 50, 51, 21))
        self.end_label.setObjectName("end_label")
        self.para_label = QtWidgets.QLabel(self.centralwidget)
        self.para_label.setGeometry(QtCore.QRect(320, 50, 91, 21))
        self.para_label.setObjectName("para_label")
        self.valueBox = QtWidgets.QLineEdit(self.centralwidget)
        self.valueBox.setGeometry(QtCore.QRect(430, 80, 113, 20))
        self.valueBox.setObjectName("valueBox")
        self.value_label = QtWidgets.QLabel(self.centralwidget)
        self.value_label.setGeometry(QtCore.QRect(430, 50, 91, 21))
        self.value_label.setObjectName("value_label")
        self.paraBox = QtWidgets.QComboBox(self.centralwidget)
        self.paraBox.setGeometry(QtCore.QRect(320, 80, 69, 22))
        self.paraBox.setObjectName("paraBox")
        self.paraBox.addItem("")
        self.paraBox.addItem("")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(580, 50, 111, 111))
        self.startButton.setObjectName("startButton")
        self.results_label = QtWidgets.QLabel(self.centralwidget)
        self.results_label.setGeometry(QtCore.QRect(20, 170, 51, 21))
        self.results_label.setObjectName("results_label")
        self.resultTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resultTable.setGeometry(QtCore.QRect(20, 201, 671, 291))
        self.resultTable.setMinimumSize(QtCore.QSize(671, 0))
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(7)
        self.resultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(6, item)
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(20, 110, 121, 21))
        self.name_label.setObjectName("name_label")
        self.nameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.nameBox.setGeometry(QtCore.QRect(20, 140, 113, 20))
        self.nameBox.setObjectName("nameBox")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(20, 510, 111, 31))
        self.exportButton.setObjectName("exportButton")
        self.pathBox = QtWidgets.QLineEdit(self.centralwidget)
        self.pathBox.setGeometry(QtCore.QRect(170, 140, 241, 20))
        self.pathBox.setObjectName("pathBox")
        self.path_label = QtWidgets.QLabel(self.centralwidget)
        self.path_label.setGeometry(QtCore.QRect(170, 110, 121, 21))
        self.path_label.setObjectName("path_label")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(170, 510, 111, 31))
        self.updateButton.setObjectName("updateButton")
        self.project_label = QtWidgets.QLabel(self.centralwidget)
        self.project_label.setGeometry(QtCore.QRect(720, 170, 91, 21))
        self.project_label.setObjectName("project_label")
        self.projectTable = QtWidgets.QTableWidget(self.centralwidget)
        self.projectTable.setGeometry(QtCore.QRect(720, 200, 161, 161))
        self.projectTable.setMaximumSize(QtCore.QSize(161, 16777215))
        self.projectTable.setObjectName("projectTable")
        self.projectTable.setColumnCount(1)
        self.projectTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.projectTable.setHorizontalHeaderItem(0, item)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(720, 420, 161, 31))
        self.clearButton.setObjectName("clearButton")
        self.value_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.value_label_2.setGeometry(QtCore.QRect(720, 30, 171, 111))
        self.value_label_2.setObjectName("value_label_2")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(720, 380, 161, 31))
        self.saveButton.setObjectName("saveButton")
        self.drawButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawButton.setGeometry(QtCore.QRect(720, 460, 161, 31))
        self.drawButton.setObjectName("drawButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(320, 510, 111, 31))
        self.addButton.setObjectName("addButton")
        self.startBox.raise_()
        self.endBox.raise_()
        self.head_label.raise_()
        self.start_label.raise_()
        self.end_label.raise_()
        self.para_label.raise_()
        self.valueBox.raise_()
        self.value_label.raise_()
        self.paraBox.raise_()
        self.startButton.raise_()
        self.results_label.raise_()
        self.resultTable.raise_()
        self.name_label.raise_()
        self.nameBox.raise_()
        self.exportButton.raise_()
        self.path_label.raise_()
        self.updateButton.raise_()
        self.pathBox.raise_()
        self.project_label.raise_()
        self.projectTable.raise_()
        self.clearButton.raise_()
        self.value_label_2.raise_()
        self.saveButton.raise_()
        self.drawButton.raise_()
        self.addButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startBox.setText(_translate("MainWindow", "229400"))
        self.endBox.setText(_translate("MainWindow", "229600"))
        self.head_label.setText(_translate("MainWindow", "ALiBaVa Search Tool"))
        self.start_label.setText(_translate("MainWindow", "Start Run"))
        self.end_label.setText(_translate("MainWindow", "End Run"))
        self.para_label.setText(_translate("MainWindow", "Search Parameter"))
        self.valueBox.setText(_translate("MainWindow", "600"))
        self.value_label.setText(_translate("MainWindow", "Search Value"))
        self.paraBox.setItemText(0, _translate("MainWindow", "Voltage"))
        self.paraBox.setItemText(1, _translate("MainWindow", "Annealing"))
        self.startButton.setText(_translate("MainWindow", "Start Search"))
        self.results_label.setText(_translate("MainWindow", "Results"))
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor Name"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Run Number"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Voltage"))
        item = self.resultTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Annealing"))
        item = self.resultTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gain"))
        item = self.resultTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Seed Signal"))
        item = self.resultTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Draw"))
        self.name_label.setText(_translate("MainWindow", "Sensor Name (optional)"))
        self.nameBox.setText(_translate("MainWindow", "KIT_Test_07"))
        self.exportButton.setText(_translate("MainWindow", "Export to File"))
        self.pathBox.setText(_translate("MainWindow", "C:\\\\Users\\\\Marius\\\\KITPlot\\\\"))
        self.path_label.setText(_translate("MainWindow", "Output path"))
        self.updateButton.setText(_translate("MainWindow", "Update Table"))
        self.project_label.setText(_translate("MainWindow", "Current Project"))
        item = self.projectTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Project Item"))
        self.clearButton.setText(_translate("MainWindow", "Clear Project"))
        self.value_label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/KIT.png\"/></p></body></html>"))
        self.saveButton.setText(_translate("MainWindow", "Save Project"))
        self.drawButton.setText(_translate("MainWindow", "Draw Project"))
        self.addButton.setText(_translate("MainWindow", ">> Add to Project"))

from Resources import Logo_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
