# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\search_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startBox = QtWidgets.QLineEdit(self.centralwidget)
        self.startBox.setGeometry(QtCore.QRect(20, 80, 113, 20))
        self.startBox.setObjectName("startBox")
        self.endBox = QtWidgets.QLineEdit(self.centralwidget)
        self.endBox.setGeometry(QtCore.QRect(170, 80, 113, 20))
        self.endBox.setObjectName("endBox")
        self.head_label = QtWidgets.QLabel(self.centralwidget)
        self.head_label.setGeometry(QtCore.QRect(20, 10, 101, 21))
        self.head_label.setObjectName("head_label")
        self.start_label = QtWidgets.QLabel(self.centralwidget)
        self.start_label.setGeometry(QtCore.QRect(20, 50, 51, 21))
        self.start_label.setObjectName("start_label")
        self.end_label = QtWidgets.QLabel(self.centralwidget)
        self.end_label.setGeometry(QtCore.QRect(170, 50, 51, 21))
        self.end_label.setObjectName("end_label")
        self.para_label = QtWidgets.QLabel(self.centralwidget)
        self.para_label.setGeometry(QtCore.QRect(320, 50, 91, 21))
        self.para_label.setObjectName("para_label")
        self.valueBox = QtWidgets.QLineEdit(self.centralwidget)
        self.valueBox.setGeometry(QtCore.QRect(430, 80, 113, 20))
        self.valueBox.setObjectName("valueBox")
        self.value_label = QtWidgets.QLabel(self.centralwidget)
        self.value_label.setGeometry(QtCore.QRect(430, 50, 91, 21))
        self.value_label.setObjectName("value_label")
        self.paraBox = QtWidgets.QComboBox(self.centralwidget)
        self.paraBox.setGeometry(QtCore.QRect(320, 80, 69, 22))
        self.paraBox.setObjectName("paraBox")
        self.paraBox.addItem("")
        self.paraBox.addItem("")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(610, 50, 111, 111))
        self.startButton.setObjectName("startButton")
        self.results_label = QtWidgets.QLabel(self.centralwidget)
        self.results_label.setGeometry(QtCore.QRect(20, 170, 51, 21))
        self.results_label.setObjectName("results_label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 201, 701, 291))
        self.tableWidget.setMinimumSize(QtCore.QSize(671, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.start_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.start_label_2.setGeometry(QtCore.QRect(20, 110, 121, 21))
        self.start_label_2.setObjectName("start_label_2")
        self.nameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.nameBox.setGeometry(QtCore.QRect(20, 140, 113, 20))
        self.nameBox.setObjectName("nameBox")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(20, 510, 111, 31))
        self.saveButton.setObjectName("saveButton")
        self.pathBox = QtWidgets.QLineEdit(self.centralwidget)
        self.pathBox.setGeometry(QtCore.QRect(170, 140, 241, 20))
        self.pathBox.setObjectName("pathBox")
        self.start_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.start_label_3.setGeometry(QtCore.QRect(170, 110, 121, 21))
        self.start_label_3.setObjectName("start_label_3")
        self.drawButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawButton.setGeometry(QtCore.QRect(170, 510, 111, 31))
        self.drawButton.setObjectName("drawButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(440, 140, 70, 17))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.head_label.setText(_translate("MainWindow", "ALiBaVa Search Tool"))
        self.start_label.setText(_translate("MainWindow", "Start Run"))
        self.end_label.setText(_translate("MainWindow", "End Run"))
        self.para_label.setText(_translate("MainWindow", "Search Parameter"))
        self.value_label.setText(_translate("MainWindow", "Search Value"))
        self.paraBox.setItemText(0, _translate("MainWindow", "Voltage"))
        self.paraBox.setItemText(1, _translate("MainWindow", "Annealing"))
        self.startButton.setText(_translate("MainWindow", "Start Search"))
        self.results_label.setText(_translate("MainWindow", "Results"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Run Number"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Voltage"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Annealing"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gain"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Seed Signal"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Draw"))
        self.start_label_2.setText(_translate("MainWindow", "Sensor Name (optional)"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.pathBox.setText(_translate("MainWindow", "C:\\\\Users\\\\Marius\\\\KITPlot\\\\"))
        self.start_label_3.setText(_translate("MainWindow", "Output path"))
        self.drawButton.setText(_translate("MainWindow", "Draw"))
        self.checkBox.setText(_translate("MainWindow", "Test"))

        self.startBox.setText(_translate("MainWindow","229400"))
        self.endBox.setText(_translate("MainWindow","229700"))
        self.valueBox.setText(_translate("MainWindow","600"))
        self.nameBox.setText(_translate("MainWindow","KIT_Test_07"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
